### ISSUE TITLE
Can't create installer file on Mac

### ISSUE THREAD

**Issue by pranulit** [ynput/ayon-launcher#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

This is what I get on the terminal:

>>> Using python [ 3.9 ]
Specify an app
>>> Creating dmg image ...
Could not find `120`
Traceback (most recent call last):
  File "/Users/pranulit/ayon-launcher/tools/build_post_process.py", line 682, in <module>
    main()
  File "/Users/pranulit/ayon-launcher/tools/build_post_process.py", line 678, in main
    create_installer(ayon_root, build_root)
  File "/Users/pranulit/ayon-launcher/tools/build_post_process.py", line 648, in create_installer
    installer_path = _create_installer(
  File "/Users/pranulit/ayon-launcher/tools/build_post_process.py", line 611, in _create_installer
    return _create_darwin_installer(*args, **kwargs)
  File "/Users/pranulit/ayon-launcher/tools/build_post_process.py", line 588, in _create_darwin_installer
    raise ValueError("Failed to create DMG image")
ValueError: Failed to create DMG image
!!!> Failed to create installer
>>> All done. You will find AYON and build log in /Users/pranulit/ayon-launcher/build directory.

_________

### Version

1.0.0

### What platform you are running on?

MacOS

### Steps To Reproduce:

1. Install AYON 1.0.4-dev.1 based on build guidelines:
 https://github.com/ynput/ayon-launcher/blob/develop/docs/build_guides/macos.md
2. try to run ./tools/make.sh make-installer

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by iLLiCiTiT** [comment]
Hello, did you run `./tools/make.sh build` before `make-installer`?

**Comment by pranulit** [comment]
Yeah, it installed the app just fine. Just having issues with the .dmg and metadata.json (for the installer) files

**Comment by iLLiCiTiT** [comment]
Could you try to run this command in terminal:
```
create-dmg --volname "AYON Installer" --windows-pos 200 120 --window-size 600 300 --app-drop-link 100 50 "
{SOME DIR}/AYON-macos.dmg" "{PATH TO CREATED .app FILE}"
```

Please replae SOME DIR with path to a directory (`~` can be used to use user home) and PATH TO CREATED .app FILE should lead to .app in build.

**Comment by pranulit** [comment]
Hmmm, gives:
- Could not find `120`

But all paths are right :/

**Comment by iLLiCiTiT** [comment]
Hmm, could you try to change `--windows-pos 200 120` in the command to `--windows-pos 200 160`, just to validate that is the `120` which could not be found.

**Comment by pranulit** [comment]
Yeah, tried it - same

**Comment by iLLiCiTiT** [comment]
We've maybe find out why it is. macOs build does require Rosetta virtualization. You have to set your terminal application to be launched with rosetta virtualization and uninstall and install again most of the packages afterwards (python, pyenv, homebrew etc.).

**Comment by pranulit** [comment]
Hmm, I'm running on Mac intel (AMD Radeon Pro 5500M 8 GB
Intel UHD Graphics 630 1536 MB, 2.3 GHz 8-Core Intel Core i9) - so Rosetta virtualization isn't really applicable?

**Comment by iLLiCiTiT** [comment]
It is, you have to run and install everything with rosetta virtualization (including terminal, cmake, pyenv, python etc.). So if you want to build it on your own, this is only way how to do it.

**Comment by pranulit** [comment]
The link you provided is for Apple Silicon. As I said I'm running on Mac intel. So all the apps are already running on rosetta essentially.

**Comment by iLLiCiTiT** [comment]
Ok, then I don't know, sorry.
