### ISSUE TITLE
Linux Mint 22 Cinnamon (Ubuntu 24.04): Build succesful, launcher refers to Rocky build

### ISSUE THREAD

**Issue by HannahFantasia** [ynput/ayon-launcher#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

AYON launcher does not open to the tray menu.
It is stuck at `AYON is updating` and closes after a while.

It creates a folder called `AYON-1.0.3-linux`
launching it through there brings more detail of an error.

### Expected Behavior:

Ayon launcher should launch as expected

after doing it 4 times, I cannot reproduce it anymore.

### Version

1.0.0

### What platform you are running on?

Linux / Ubuntu

### Steps To Reproduce:

Follow these steps:

set up pyenv:
https://forums.linuxmint.com/viewtopic.php?f=42&p=2103213

add deadsnakes to my package manager through:
`sudo add-apt-repository ppa:deadsnakes/ppa`

update my repositories:
`sudo apt update`

install distutils like the mention:
`sudo apt install python3.9-distutils`

install QT based on n0rbert´s response:
https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04:
`sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools`

install libxcb-cursor based on the suggestion:
`sudo apt install libxcb-cursor0`

clone repo:
`git clone https://github.com/ynput/ayon-launcher`

prep env:
`./tools/make.sh create-env`
`./tools/make.sh install-runtime-dependencies`

build and create installer:
`./tools/make.sh build`

`./tools/make.sh make-installer`

launch installer
`./ayon`

fill in credentials

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
When it runs, 

Running it from the AYON installable folder:


~/AYON-1.0.4-dev.1-linux$ ./ayon
/home/hannah/.local/share/Trash/files/AYON-1.0.4-dev.1-linux/dependencies/blessed/terminal.py:183: UserWarning: Failed to setupterm(kind='xterm-256color'): setupterm: could not find terminal
  warnings.warn(msg)
Created local site id "rainbow-honest-vicugna"
!!! Got invalid credentials.
AYON Server URL is not set.
/home/hannah/.local/share/Trash/files/AYON-1.0.4-dev.1-linux/dependencies/blessed/terminal.py:183: UserWarning: Failed to setupterm(kind='xterm-256color'): setupterm: could not find terminal
  warnings.warn(msg)
/home/hannah/.local/share/Trash/files/AYON-1.0.4-dev.1-linux/dependencies/blessed/terminal.py:183: UserWarning: Failed to setupterm(kind='xterm-256color'): setupterm: could not find terminal
  warnings.warn(msg)
Extracting /home/hannah/Downloads/AYON-1.0.3-linux-rocky9.tar.gz -> /home/hannah/.local/share/Trash/files
Traceback (most recent call last):
  File "__startup__.py", line 120, in run
  File "console.py", line 16, in run
  File "start.py", line 990, in <module>
  File "start.py", line 980, in main
  File "start.py", line 724, in boot
  File "start.py", line 691, in _start_distribution
  File "subprocess.py", line 349, in call
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1837, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/hannah/.local/share/Trash/files/AYON-1.0.3-linux-rocky9/ayon'
```

Doing it again gives a similar error but says that it can connect to the address:
```
~/AYON-1.0.4-dev.1-linux$./ayon
/home/hannah/AYON-1.0.4-dev.1-linux/dependencies/blessed/terminal.py:183: UserWarning: Failed to setupterm(kind='xterm-256color'): setupterm: could not find terminal
  warnings.warn(msg)
>>> Connected to AYON server http://34.170.83.247:5000
/home/hannah/AYON-1.0.4-dev.1-linux/dependencies/blessed/terminal.py:183: UserWarning: Failed to setupterm(kind='xterm-256color'): setupterm: could not find terminal
  warnings.warn(msg)
Extracting /home/hannah/Downloads/AYON-1.0.3-linux-rocky9.tar.gz -> /home/hannah
Traceback (most recent call last):
  File "__startup__.py", line 120, in run
  File "console.py", line 16, in run
  File "start.py", line 990, in <module>
  File "start.py", line 980, in main
  File "start.py", line 724, in boot
  File "start.py", line 691, in _start_distribution
  File "subprocess.py", line 349, in call
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1837, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/hannah/AYON-1.0.3-linux-rocky9/ayon'
```

using the `./ayon` command also creates a new launcher folder with the version `AYON-1.0.3-linux`
when deleting it, it creates it again, when running `./ayon` on `AYON-1.0.4-dev.1-linux` it functions correctly. It also does when running it from `AYON-1.0.3-linux`

which gives expected behaviour:

```
hannah@desktop:~/AYON-1.0.3-linux$ ./ayon
/home/hannah/.local/share/Trash/files/AYON-1.2.0.3-linux/dependencies/blessed/terminal.py:183: UserWarning: Failed to setupterm(kind='xterm-256color'): setupterm: could not find terminal
  warnings.warn(msg)
>>> Connected to AYON server http://34.170.83.247:5000
/home/hannah/.local/share/Trash/files/AYON-1.2.0.3-linux/dependencies/blessed/terminal.py:183: UserWarning: Failed to setupterm(kind='xterm-256color'): setupterm: could not find terminal
  warnings.warn(msg)
*** AYON [1.0.3] -------------------------------------------------------------
>>> Using AYON from [ /home/hannah/.local/share/Trash/files/AYON-1.2.0.3-linux ]
... AYON variant: [ production ]
... AYON bundle:  [ 2024.06.1-full_kitsu-2024-07-07-02_PR03 ]
>>> loading environments ...
  - global AYON ...
  - for addons ...
Registered font families: Noto Sans, Noto Sans, Noto Sans, Noto Sans, Noto Sans Mono, Noto Sans Mono SemiBold, Noto Sans Mono, Noto Sans Mono ExtraLight, Noto Sans Mono, Noto Sans Mono ExtraBold, Noto Sans Mono, Noto Sans Mono Thin, Noto Sans Mono, Noto Sans Mono Light, Noto Sans Mono, Noto Sans Mono Medium, Noto Sans Mono, Noto Sans Mono, Noto Sans Mono Black, Noto Sans Mono
WARNING:TrayAddonsManager:Addon "kitsu" crashed on `tray_start`.
Traceback (most recent call last):
  File "/home/hannah/.local/share/AYON/addons/core_0.4.0/ayon_core/addon/base.py", line 1490, in start_addons
    addon.tray_start()
  File "/home/hannah/.local/share/AYON/addons/kitsu_1.2.2/ayon_kitsu/addon.py", line 61, in tray_start
    raise
RuntimeError: No active exception to reraise
------------------+-----------+--------------+---------+---------------+---------+------------+-----
Addon name        |Version    |Initialization|Tray init|Connect modules|Tray menu|Addons start|Total
------------------+-----------+--------------+---------+---------------+---------+------------+-----
applications      |0.2.4      |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
ayon_ocio         |1.1.1      |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
ayon_third_party  |1.1.1      |0.000         |0.000    |0.000          |0.000    |0.432       |0.433
blender           |0.2.1-dev.1|0.000         |N/A      |0.000          |N/A      |N/A         |0.000
celaction         |0.2.0      |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
deadline          |0.2.2      |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
kitsu             |1.2.2      |0.000         |0.000    |0.000          |0.000    |0.077       |0.077
launcher_tool     |1.0.0      |0.000         |0.052    |0.000          |0.000    |0.000       |0.052
loader_tool       |1.0.0      |0.000         |0.032    |0.000          |0.000    |0.000       |0.032
python_interpreter|1.0.0      |0.000         |0.010    |0.000          |0.000    |0.000       |0.010
royalrender       |0.2.1      |0.000         |N/A      |N/A            |N/A      |N/A         |0.000
sitesync          |1.1.2      |0.000         |0.340    |0.000          |0.000    |0.000       |0.341
traypublisher     |0.2.4      |0.000         |0.000    |0.000          |0.000    |0.000       |0.000
tvpaint           |0.2.2      |0.000         |N/A      |0.000          |N/A      |N/A         |0.000
webserver         |1.0.0      |0.000         |0.143    |0.000          |0.010    |0.000       |0.154
------------------+-----------+--------------+---------+---------------+---------+------------+-----
Total             |(15)       |0.001         |0.577    |0.000          |0.011    |0.510       |1.099

/home/hannah/.local/share/Trash/files/AYON-1.2.0.3-linux/dependencies/blessed/terminal.py:183: UserWarning: Failed to setupterm(kind='xterm-256color'): setupterm: could not find terminal
  warnings.warn(msg)
>>> [  Starting SiteSync  ] 
>>> [  SiteSync Started  ] 
>>> [  Starting WebServer server  ] 
```
```


### Additional context:

I run the latest installation with updated packages of `Linux Mint 22 Cinnamon`

**Comment by ddesmond** [comment]
I have the same thing with rocky deps not workging on centos7 in 1.0.4.dev1 from develop branch.

**Comment by iLLiCiTiT** [comment]
This is wild guess, but I think you did bootstrap? Bootstrap contains rocky9 installer and dependency package. To use different linux distribution please build a new one and make sure it is used in your bundle. The output here says that you've launched 1.0.4-dev.1 but you production bundle require 1.0.3, so it downloaded it (that was the updating window) and launched it, but because 1.0.3 is for rocky9 it crashed. The same would happen with dependency packages, you have to prepare them for different distributions.
