### ISSUE TITLE
Explore here: Folder does not exist.

### ISSUE THREAD

**Issue by beatreichenbach** [ynput/ayon-launcher#55]
I followed the guide here: https://github.com/ynput/ayon-docker, installed the server, then downloaded the launcher, made an example project and getting this when I try to explore here from the launcher:

```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\addons\openpype_3.17.0\openpype\tools\launcher\window.py", line 411, in run_action
    action().process(filtered_session)
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\addons\openpype_3.17.0\openpype\plugins\actions\open_file_explorer.py", line 34, in process
    path = self._get_workdir(project_name, asset_name, task_name)
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\addons\openpype_3.17.0\openpype\plugins\actions\open_file_explorer.py", line 88, in _get_workdir
    raise AssertionError("Folder does not exist.")
AssertionError: Folder does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1086, in emit
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "__startup__.py", line 120, in run
  File "console.py", line 16, in run
  File "start.py", line 602, in <module>
  File "start.py", line 598, in main
  File "start.py", line 490, in main_cli
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\app\AYON 1.0.0-beta.5\dependencies\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\app\AYON 1.0.0-beta.5\dependencies\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\app\AYON 1.0.0-beta.5\dependencies\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\app\AYON 1.0.0-beta.5\dependencies\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\app\AYON 1.0.0-beta.5\dependencies\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\app\AYON 1.0.0-beta.5\dependencies\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\addons\openpype_3.17.0\openpype\cli.py", line 58, in main
    ctx.invoke(tray)
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\app\AYON 1.0.0-beta.5\dependencies\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\addons\openpype_3.17.0\openpype\cli.py", line 78, in tray
    PypeCommands().launch_tray()
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\addons\openpype_3.17.0\openpype\pype_commands.py", line 22, in launch_tray
    tray.main()
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\addons\openpype_3.17.0\openpype\tools\tray\pype_tray.py", line 873, in main
    sys.exit(app.exec_())
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\addons\openpype_3.17.0\openpype\tools\launcher\widgets.py", line 325, in on_clicked
    self.action_clicked.emit(action)
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\addons\openpype_3.17.0\openpype\tools\launcher\window.py", line 382, in on_action_clicked
    self.run_action(action)
  File "C:\Users\Beat\AppData\Local\Ynput\AYON\addons\openpype_3.17.0\openpype\tools\launcher\window.py", line 413, in run_action
    self.log.warning("Action launch failed.", exc_info=True)
  File "logging\__init__.py", line 1458, in warning
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1091, in emit
Message: 'Action launch failed.'
Arguments: ()

```

**Comment by iLLiCiTiT** [comment]
Hello, please move the issue to https://github.com/ynput/OpenPype repository where the related code is.
